Write-Host "CIPP Consultant Agent local frontend workflow"
Write-Host ""
Write-Host "1. Start backend:"
Write-Host "   cipp-run-dev-api --host 127.0.0.1 --port 8000"
Write-Host ""
Write-Host "2. Start frontend:"
Write-Host "   cd apps/web"
Write-Host "   npm run dev"
Write-Host ""
Write-Host "3. Open:"
Write-Host "   http://127.0.0.1:5173"
Write-Host ""
Write-Host "Mock UI without backend:"
Write-Host "   http://127.0.0.1:5173/?mock=1"
